name: crs-insurance-adaptation-fl
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - requests
  - pyyaml
  - statsmodels
  - linearmodels
  - matplotlib
  - scipy
  - pip
  - pip:
      - pytest
